### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by danielramandi** [UBC-MDS/customer_complaint_analyzer#29]
Congratulations on finishing milestone 1! We can see you put a lot of work into this project, nice work! Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project. 

**1. License:**

- [x] A creative commons license needs to be included to specify how non-code/software work can be used, shared, and derived. -2

**Comment:** The CC license is mainly used for data and non-code-related work. The results and findings of your project will be mainly covered by the CC lic. It is good practice to add that to your lic as well.

**2. Project proposal**

- [x] The clarity of README could be improved through additional changes. -1

**Comment:** The type and structure of the data are unclear. It is hard to follow the questions when the structure of the dataset is not explained. I suggest adding a paragraph or section on the data (what/how many types of features it has, what the target is, etc.) This is even more important when the link to the dataset also does not provide a further explanation of the dataset structure.
Also, of important note, the EDA report is not easily found. There are multiple notebooks on the EDA. I suggest removing those that are not necessary. 

**3. A script that downloads and saves the data**

- [x] A first copy of the data must be saved in the data directory (and ideally in the data/raw subdirectory. -1

**Comment:** This should be done through the argument input to the script rather than the code in the script. I suggest having your input to the script as a path, rather than a filename. This helps reproducibility and helps users modify modules easily. 

**4. Exploratory data analysis in a literate code document**
The EDA report needs some additions and modifications. Here are some points and comments that could help:

- [x] The document contains some problems. For instance, a plot that is not rendered correctly. -1

- [x] There are no figure captions. -2 viz

- [x] The captions for the tables should be above the table. -1 viz

**Comment:** Providing titles, captions, figure/table numbers, etc. makes it easier to refer to them in the text. It also helps in understanding and following the flow of the report. 

- [x] There are less than the required 2 plots and one table -2

- [ ] Missing a summary/abstract in the analysis (.ipynb or .Rmd) file -2

- [ ] There is no title, introduction, and/or references in the analysis (.ipynb or .Rmd) file -2

**Comment:** The EDA does not provide enough insight into the data. Adding a few tables and plots could be more helpful. Try using subplots to combine similar plots, or pointing towards the same point or concept. Also, the title and intro as well as references are missing. I suggest also adding a conclusion/discussion part at the end and highlighting any interesting findings in the EDA. The EDA should help you in the analysis and model-building process by giving you insight into the data. 

- [ ] The narration of methods and method choices was not as clear and thorough as expected. -1

- [ ] The introduction should identify and describe the dataset that was used to answer the question. -1

**Comment:**  The explanation of the data cleaning process is not clear or provided. This is part is very important, as untransparent data-cleaning strategies can heavily affect the reproducibility of the analysis.

**5. Expectation**

- [x] All contributions are expected to go through code review via a pull request. A branch protection rule should be set in the main branch. There shouldn't exist commits in the main branch, except the ones created when you merged branches. -2

**Comment:** Based on the contributing.md explanations, all the members should only commit to branches and merge to the main branch. This is a very good practice (though not the only one), but there are commits on the main branch outside the merges. Make sure to either modify your contribution policies or not commit to the main branch (except for the merges).

- [x] All the team members should have meaningful commits to the project -5

**Comment:** The number of commits is very variable between group participants. If this is how you divided your project load, please be more specific about it on the teamwork contract.

**Overall comment:** The project is well designed and the dataset is chosen wisely to fit the project. The question is clear and the structure of the repo looks good. However, a few improvements in the EDA report would make it more engaging and easier to follow and understand. Well done and good luck with the rest of the project.
