### ISSUE TITLE
Milestone 2 Comments

### ISSUE THREAD

**Issue by Glenn032787** [UBC-MDS/customer_complaint_analyzer#51]
**Congratulations on finishing milestone 2!** We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.  

We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.

#### 1.1 Analysis code is abstracted to four (or more) scripts which take command line arguments and save analysis artifacts (e.g., figures and data for tables).

- [ ] Code in one or more scripts is not of high quality, or does not adhere to the adopted code styles for the course: author, date and where the script has been extracted from (if it is a re-used script), should be added **-2**  **quality**
**Comment:** Author and date should be included in generate_eda.py

#### 1.2 Report is written in a literate code document, and the code in the literate code document primarily functions to source analysis artifacts and format the document.

- [ ] The `proposal.md` file has been created and moved to the `doc` directory **-2** **mechanics**

### 1.3 Code is abstracted to functions with good function design
  
- [x] There are cases of functions that are too big and could be improved by defining utility functions. **-1** **reasoning**
**Comment:** The main function in analysis.py is quite large. Would be good to sepperate them out into smaller functions. I would also suggest writing a function for making pipeline and cross validating which takes in a model as input so it does not need to be rewritten multiple times.

- [ ] There are cases of functions that do not check for proper input and/or do not provide useful error messages. **-1** **mechanics**
**Comment:** Would be good to check for inputs using try-except (ie error when trying to read in a file that doesn't exist)
### 1.4 Functions are well documented
 Good Job!

#### 1.5 Code is called in the analysis
Good Job!

---

##### From these 7 points remove points if:
- [ ] There is no documentation. It is not clear what the tests are testing. **-3** **quality**
**Comment:** It is great that you included thorough test however, it would be good to add some documentation is explain what each test is testing for.
---

#### 1.9 Dependencies have been updated (so it include the test libraries)

Good Job!

#### 2.1 GitHub Issues

Good Job!

#### 2.2 Follows GitHub flow version control workflow
Good Job!

### 3. Project file and directory structure organization

- [ ] There are folder/files that should not be committed. Including a `.gitignore` file is recommended. **- 1** **reasoning**
**Comment:** Should remove .Rhistory and .vscode from git repository
### 3.1 Analysis can be run reproducibly using documentation provided in the README

- [x] Could not reproducibly run the analysis because the code fails. **-3** **accuracy**
**Comment:** Error when running generate_eda.py. Make sure to run everything from scratch to ensure everything is reproducible. 

### 4. Submission expectations

- [x] Please provide the link to the release as `https://github.com/UBC-MDS/REPOSITORY/tree/VERSION` (replacing `REPOSITORY` and `VERSION` with the correct ones for your project version for each milestone). This makes is a lot easier for someone to just visit the repository as it was at that point in the project's history. **-1** **mechanics**

**Comment by tieandrews** [comment]
@Glenn032787 for 1.2 above, it's not clear why we did this wrong other than instead of `doc` we named our folder `reports` and our report file name is different as `final_report` but properly descriptive of what it actually is. Can you clarify what I'm missing with this specific aspect? Thanks.

**Comment by Glenn032787** [comment]
1.2 is intended for you archive the proposal you wrote in milestone 1 (in the readme.md) in `doc/proposal.md` file. But I check that you just added onto the milestone 1 readme.md file rather than overwrite it so I won't deduct the marks.
